# Generated by Django 3.0.3 on 2020-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200330_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
